#set the parmater here
#mode descript the structure of the files that contains the measurement on each window
#modes: ['40_100','40_100#body_wave','40_100#surface_wave','40_100']
mode: "40_100#surface_wave"
#Event id
event_id : 'C200610160035A'
#########################
par_file : 'params/proc_synt.40_100.param.yml'
#Get the net.stn
net_stn  : "G.KIP"
#Set the period band
periodband : '40_100'
