# Path to windows
path_wid: "/mnt/tigress/TROMP/data/DATA_M25/window"
# Path to observed data and synthetic data
path_obs: "/mnt/tigress/TROMP/data/DATA_M25/proc_obsd"
path_syn: "/mnt/tigress/TROMP/data/DATA_M25/proc_synt"
# Set the modes corresponds to particular data files
# modes: ['17_40','40_100#body_wave','40_100#surface_wave','90_250']
#Event id and names of processed observation and synthetic files
event_id :    'C201407041500A'
proc_obs_file: C201407041500A.proc_obsd_40_100.h5
proc_syn_file: C201407041500A.proc_synt_40_100.h5
# File containing the windows
win_file: windows.filter.json
# Network and station
#net_stn : 'G.PVC'
#net_stn : ['IU.AFI']
#net_stn : ['G.PPTF']
#net_stn : ['XU.DOTA']
#net_stn : ['G.PVC','IU.CTAO']
net_stn : ['G.TAOE']
#Set the period band
periodband   : '40_100'
#Set the x-limit of the axis
x_lm_left: 0.0
x_lm_right: 3200
#Color List
fcolors: ['#E56B51','grey','yellow','green','olive','orange','lime','darkorange','black','red','teal','navy','snow','coral','tomato','darkred','brown',
                'magenta','aqua','cyan','plum','indigo','pink','hotpink','skyblue','tan','turquoise','seagreen','springgreen', 'crimson', 'gold','grey']
