#parameter for histogram plot
#Path of the data
path: '/mnt/tigress/TROMP/data/DATA_M25/window'
#FILES of Regional station file
FstnName: 'REGIONAL_EVENTS_and_STATIONS/STATIONS_GLADM25_in_CHUNK.dat'
##File for regional events
FevtName: 'REGIONAL_EVENTS_and_STATIONS/EVENTS_GLADM25_in_CHUNK.dat'
#ALL mode used in the full waveform inversion
#modes: ['17_40','40_100#body_wave','40_100#surface_wave','90_250']
modes: ['17_40']
#modes: ['40_100#surface_wave']
WaveTpes: {'17_40_in_Chunk.dat':'Body wave 17-40 s', '40_100_body_wave_in_Chunk.dat': 'Body wave 40-100 s', 
            '40_100_surface_wave_in_Chunk.dat': 'Surf wave 40-100 s', '90_250_in_Chunk.dat' : 'Surf wave 90-250 s'}
##########
#WaveTpes: {'17_40_in_Chunk_sorted.dat':'Body wave 17-40 s', '40_100_body_wave_in_Chunk_sorted.dat': 'Body wave 40-100 s', 
#            '40_100_surface_wave_in_Chunk_sorted.dat': 'Surf wave 40-100 s', '90_250_in_Chunk_sorted.dat' : 'Surf wave 90-250 s'}
#Set the percentiles of the trim data and the original data
path_average: True
path_absolue: False
#Original data percentiles
percs_O: [0,100]
#Trim data percentiles
#percs: [3,95.5]
percs: [3,97]
#Set the position were the text should been writen on the figure
#t1 : -1.45
t1 : -1.15
#Right time-limit
#t2 : 1.45
t2 : 1.15
#Y-Axis limit
Ymin : 0.0
Ymax : 2.25
#Ymin : 0.0
#Ymax : 2.0
#X-Axis limit
Xmin : -1.5
Xmax :  1.5
#Xmin : -2.5
#Xmax :  2.5
#Fonte for text
fontsize_Title : 18
fontsize_Label : 18
fontsize_Txt   : 17
fsize_abc      : 25
#fsize_abc      : 35
